DROP TABLE IF EXISTS sample_source;
DROP TABLE IF EXISTS sample;

CREATE TABLE IF NOT EXISTS sample_source (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS sample (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);