name: Backend Batch Server CI

on:
  push:
    branches: [ "develop", "feature/**" ]
    paths:
      - 'batch-server/**'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'batch-server/**'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      statuses: write
      checks: write
      pull-requests: write