name: Backend Batch Server CI

on:
  workflow_dispatch:

  push:
    branches: [ "develop", "feature/**" ]
    paths:
      - 'batch-server/**'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'batch-server/**'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      statuses: write
      checks: write
      pull-requests: write

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0